#!/bin/sh

# Gancho para mensajes urgentes (de disparo)
#
# O contenido da mensaje é passado como um parámetro de
# linha de comando ($1).
#
# Modifique este script para que a mensaje seja repassada
# via e-mail, SMS, Telegram, PushOver, etc. Ou remova seu
# contenido para que ele no faça nada (o script precisa
# existir e ser executável, mesmo que no faça nada.)

echo "$1" >> gancho_msg.txt
