#!/bin/sh

# Gancho para fotos (de disparo)
#
# O nome do archivo é passado como parámetro ($1)
#
# Modifique este script para que a mensaje seja repassada
# via e-mail, SMS, Telegram, PushOver, etc. Ou remova seu
# contenido para que ele no faça nada (o script precisa
# existir e ser executável, mesmo que no faça nada.)

echo "$1" >> gancho_archivo.txt
